development:
  adapter: postgresql
  encoding: unicode
  database: full_caching_example_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: full_caching_example_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: full_caching_example_production
  pool: 5
